# numpy

In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np 


In [4]:
list = [1,2,3]
list

[1, 2, 3]

In [7]:
arr1 = np.array(list)
print(arr1)

[1 2 3]


In [6]:
print(np.__version__)

2.3.5


In [9]:
print(type(arr1))
      

<class 'numpy.ndarray'>


In [10]:
print(arr1.ndim)

1


In [12]:
list1 = [1,2,3]
list2 = [4,5,6]
arr2 = np.array([list1,list2])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [13]:
print(arr2.ndim)

2


In [14]:
print(type(arr2))

<class 'numpy.ndarray'>


In [10]:
listA = [2,4,6]
listB = [3,6,9]
listC = [4,8,13]
arr3 = np.array([[listA,listB,listC]])
print(arr3)

[[[ 2  4  6]
  [ 3  6  9]
  [ 4  8 13]]]


In [11]:
 print("shape", arr3.shape)

shape (1, 3, 3)


In [9]:
zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
full_arr = np.full((3,4),7)
print(full_arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [16]:
id_arr = np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
print(np.empty(2))

[-4.20665877e+103  2.59932495e-102]


In [22]:
print(np.arange(2,20,2))


[ 2  4  6  8 10 12 14 16 18]


In [24]:
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]


In [26]:
r_arr = np.random.rand(2,3)
print(r_arr)

[[0.31274118 0.7572187  0.68101914]
 [0.28246924 0.41526426 0.7967086 ]]


In [40]:
r2_arr = np.random.randint(1,100,(3,4))
print(r2_arr)

[[59 30 45 40]
 [30 52 80 51]
 [61 49 19 40]]


In [30]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [31]:
print(a[0])

1


In [32]:
print(a[-1])

5


In [35]:
arr6 = np.array([[1,2,3],[3,4,5]])
print(arr6)

[[1 2 3]
 [3 4 5]]


In [36]:
print(arr6[: , 0])

[1 3]


In [37]:
print(arr6[:,1])

[2 4]


In [40]:
ar7 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar7)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
print(ar7[0])

[1 2 3]


In [42]:
print(ar7[0][2])

3


In [43]:
print(ar7[:,0])

[1 4 7]


In [45]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [48]:
reshape = arr.reshape(4,1)
print(reshape)

[[1]
 [2]
 [3]
 [4]]


In [53]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [3]:
%%time
numbers = list(range(1,10000000001))
result = [x+5 for x in numbers ]

CPU times: total: 0 ns
Wall time: 857 μs


MemoryError: 

In [4]:
%%time 
numbers = np.arange(1,1000001)
result = numbers+5
result

CPU times: total: 0 ns
Wall time: 9.62 ms


array([      6,       7,       8, ..., 1000003, 1000004, 1000005],
      shape=(1000000,))

In [3]:
a = np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [5]:
print(a+10)
print(a-10)
print(a*3)
print(a/2)

[20 30 40 50 60]
[ 0 10 20 30 40]
[ 30  60  90 120 150]
[ 5. 10. 15. 20. 25.]


In [6]:
print(np.square(a))

[ 100  400  900 1600 2500]


In [8]:
a = np.array([10,20,30])
b = np.array([10,80,30])
print(a)
print(b)

print(a==b)
print(np.array_equal(a,b))

[10 20 30]
[10 80 30]
[ True False  True]
False


In [15]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[40 70 90]
[-20 -30 -30]
[ 300 1000 1800]
[0.33333333 0.4        0.5       ]


In [16]:
print(np.dot(a,b))

3100


In [18]:
a = np.array([[10,20,30],[40,50,60]])
print(a)

[[10 20 30]
 [40 50 60]]


In [19]:
print(a.T)

[[10 40]
 [20 50]
 [30 60]]


In [14]:
c = np.array([10,20,30])
d = np.array([5])
e = np.array([20,40,60])
print(c+d+e)

[35 65 95]


In [18]:
data = np.array([10,20,40, np.nan , 50 , np.inf])
print(data)

[10. 20. 40. nan 50. inf]


In [19]:
print(np.isnan(data))

[False False False  True False False]


In [20]:
arr = np.array([1,0,0,9])
print(arr)
np.save('my_array.npy',arr)

[1 0 0 9]


In [21]:
loaded = np.load('my_array.npy')
print(loaded)

[1 0 0 9]


In [29]:
a = np.arange(1,11,1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [24]:
b = np.array([[10,20,30],[40,50,60]])
print(b)

[[10 20 30]
 [40 50 60]]


In [34]:
print (a.shape)

(10,)


In [35]:
print(a.size)

10


In [41]:
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


In [5]:
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
ones = np.ones((4,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
arrange = np.arange(0,20,2)
print(arrange)

[ 0  2  4  6  8 10 12 14 16 18]


In [13]:
linspace = np.linspace(1,10,5)
print(linspace)

[ 1.    3.25  5.5   7.75 10.  ]


In [14]:
one_d = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(one_d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [16]:
reshape1 = one_d.reshape(3,4)
print(reshape1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
reshape2 = one_d.reshape(2,6)
print(reshape2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [24]:
arr = np.array([10,20,30,40,50])
print(arr)
print("second element is ",arr[1])
print("fourth element is " ,arr[3])
print(arr[1:3])


[10 20 30 40 50]
second element is  20
fourth element is  40
[20 30]


In [29]:
a = np.array([10,20,30])
b = np.array([40,50,60])
add = np.add(a,b)
print("sum of two array is " , add)
sub = np.subtract(a,b)
print("difference of two array is " , sub)
multiply = np.multiply(a,b)
print("product of two array is " , multiply )
divide = np.divide(a,b)
print ("divison of two array is " , divide)

sum of two array is  [50 70 90]
difference of two array is  [-30 -30 -30]
product of two array is  [ 400 1000 1800]
divison of two array is  [0.25 0.4  0.5 ]


In [34]:
a = np.array ([20,40,60,80,100])
print(a)
print("minimun value is ", np.min(a))
print("maximum value is " , np.max(a))
print("avg is " , np.average(a))

[ 20  40  60  80 100]
minimun value is  20
maximum value is  100
avg is  60.0


In [41]:
randomnumbers = np.random.rand(5)
print(randomnumbers)

[0.12067974 0.50015892 0.01633394 0.06135782 0.69864111]


In [42]:
random = np.random.randint(1,10,(3,3))
print(random)

[[1 9 7]
 [5 3 2]
 [1 3 5]]


In [43]:
arr = np.array([5,10,15,20,25])
for i in arr:
    if i >10:
        print(i)

15
20
25
